name: .NET CI Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout Source Code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # - name: Restore Dependencies
    #   run: dotnet restore
      
    - name: Restore dependencies
      run: dotnet restore DotNetDemo.csproj
  
    - name: Build Project
      run: dotnet build --configuration Release --no-restore

    - name: Execute Unit Tests
      run: dotnet test --no-build

    - name: Publish Application
      run: dotnet publish DotNetDemo/DotNetDemo.csproj -c Release -o publish

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-build
        path: publish
